// Code generated by MockGen. DO NOT EDIT.
// Source: financial_transaction_interface.go

// Package repositorytest is a generated GoMock package.
package repositorytest

import (
	domain "financial-transaction-system/app/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFinancialTransactionRepository is a mock of FinancialTransactionRepository interface.
type MockFinancialTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFinancialTransactionRepositoryMockRecorder
}

// MockFinancialTransactionRepositoryMockRecorder is the mock recorder for MockFinancialTransactionRepository.
type MockFinancialTransactionRepositoryMockRecorder struct {
	mock *MockFinancialTransactionRepository
}

// NewMockFinancialTransactionRepository creates a new mock instance.
func NewMockFinancialTransactionRepository(ctrl *gomock.Controller) *MockFinancialTransactionRepository {
	mock := &MockFinancialTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockFinancialTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinancialTransactionRepository) EXPECT() *MockFinancialTransactionRepositoryMockRecorder {
	return m.recorder
}

// CreateNewAccount mocks base method.
func (m *MockFinancialTransactionRepository) CreateNewAccount(account *domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewAccount", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewAccount indicates an expected call of CreateNewAccount.
func (mr *MockFinancialTransactionRepositoryMockRecorder) CreateNewAccount(account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewAccount", reflect.TypeOf((*MockFinancialTransactionRepository)(nil).CreateNewAccount), account)
}

// GetAccountByID mocks base method.
func (m *MockFinancialTransactionRepository) GetAccountByID(id int64) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", id)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockFinancialTransactionRepositoryMockRecorder) GetAccountByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockFinancialTransactionRepository)(nil).GetAccountByID), id)
}

// GetAllTransactions mocks base method.
func (m *MockFinancialTransactionRepository) GetAllTransactions() ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTransactions")
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTransactions indicates an expected call of GetAllTransactions.
func (mr *MockFinancialTransactionRepositoryMockRecorder) GetAllTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTransactions", reflect.TypeOf((*MockFinancialTransactionRepository)(nil).GetAllTransactions))
}

// GetTransactionByIdempotencyKey mocks base method.
func (m *MockFinancialTransactionRepository) GetTransactionByIdempotencyKey(arg0 string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByIdempotencyKey", arg0)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByIdempotencyKey indicates an expected call of GetTransactionByIdempotencyKey.
func (mr *MockFinancialTransactionRepositoryMockRecorder) GetTransactionByIdempotencyKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByIdempotencyKey", reflect.TypeOf((*MockFinancialTransactionRepository)(nil).GetTransactionByIdempotencyKey), arg0)
}

// PerformTransaction mocks base method.
func (m *MockFinancialTransactionRepository) PerformTransaction(arg0 *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformTransaction", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformTransaction indicates an expected call of PerformTransaction.
func (mr *MockFinancialTransactionRepositoryMockRecorder) PerformTransaction(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformTransaction", reflect.TypeOf((*MockFinancialTransactionRepository)(nil).PerformTransaction), arg0)
}
