// Code generated by MockGen. DO NOT EDIT.
// Source: service_interface.go

// Package repositorytest is a generated GoMock package.
package repositorytest

import (
	domain "financial-transaction-system/app/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFinancialTransactionService is a mock of FinancialTransactionService interface.
type MockFinancialTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockFinancialTransactionServiceMockRecorder
}

// MockFinancialTransactionServiceMockRecorder is the mock recorder for MockFinancialTransactionService.
type MockFinancialTransactionServiceMockRecorder struct {
	mock *MockFinancialTransactionService
}

// NewMockFinancialTransactionService creates a new mock instance.
func NewMockFinancialTransactionService(ctrl *gomock.Controller) *MockFinancialTransactionService {
	mock := &MockFinancialTransactionService{ctrl: ctrl}
	mock.recorder = &MockFinancialTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinancialTransactionService) EXPECT() *MockFinancialTransactionServiceMockRecorder {
	return m.recorder
}

// CreateNewAccount mocks base method.
func (m *MockFinancialTransactionService) CreateNewAccount(arg0 *domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewAccount", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewAccount indicates an expected call of CreateNewAccount.
func (mr *MockFinancialTransactionServiceMockRecorder) CreateNewAccount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewAccount", reflect.TypeOf((*MockFinancialTransactionService)(nil).CreateNewAccount), arg0)
}

// GetAccountById mocks base method.
func (m *MockFinancialTransactionService) GetAccountById(arg0 int64) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountById", arg0)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountById indicates an expected call of GetAccountById.
func (mr *MockFinancialTransactionServiceMockRecorder) GetAccountById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountById", reflect.TypeOf((*MockFinancialTransactionService)(nil).GetAccountById), arg0)
}

// GetAllTransactions mocks base method.
func (m *MockFinancialTransactionService) GetAllTransactions() ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTransactions")
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTransactions indicates an expected call of GetAllTransactions.
func (mr *MockFinancialTransactionServiceMockRecorder) GetAllTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTransactions", reflect.TypeOf((*MockFinancialTransactionService)(nil).GetAllTransactions))
}

// GetTransactionByIdempotencyKey mocks base method.
func (m *MockFinancialTransactionService) GetTransactionByIdempotencyKey(key string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByIdempotencyKey", key)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByIdempotencyKey indicates an expected call of GetTransactionByIdempotencyKey.
func (mr *MockFinancialTransactionServiceMockRecorder) GetTransactionByIdempotencyKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByIdempotencyKey", reflect.TypeOf((*MockFinancialTransactionService)(nil).GetTransactionByIdempotencyKey), key)
}

// PerformTransaction mocks base method.
func (m *MockFinancialTransactionService) PerformTransaction(txn *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformTransaction", txn)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformTransaction indicates an expected call of PerformTransaction.
func (mr *MockFinancialTransactionServiceMockRecorder) PerformTransaction(txn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformTransaction", reflect.TypeOf((*MockFinancialTransactionService)(nil).PerformTransaction), txn)
}
